Shamil
processtech/runawfe-devstudio pull request #151
Opened 2020-03-25 14:40 UTC by MIoCJluTeJllo

1, 2, 5 и часть 3 задачи. Именно по функционалу. Внутри новые классы еще будут переделаны

2020-06-16 21:27 UTC, technokratos requested changes
Main remarks: reduce dependency, clear comments, remove code duplications.

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/GraphitiGlobalSectionEditor.java
> +            // getDiagramEditorPage().getContentEditPart().refresh();
Закоменченный код

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/gef/part/tree/ElementTreeEditPart.java
> +    		setWidgetText(getModel().getLabel().substring(1));
Какой-то магический код. Здесь нужны какие-то комментарии. 
а куда делся вызов setWidgetText(getModel().getLabel()); для всех остальных типов моделей? Он точно не нужен.
В принципе текущие решение плохое, базовый класс шаблона дерево, ничего не должен знать о том какие наследники есть у его вложенного класса. 
В крайнем случае у моделей можно добавить новый метод в GraphElement,  getVisiableLable() по умолчанию возвращает getLabel, а для GlobalSectionDefinistion уже выполняется специфичный код.

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/SwimlaneEditorPage.java
> +            	if (getDefinition() instanceof GlobalSectionDefinition) {
Тоже плохое решение, как вариант добавить метод пустой метод removeGlobalSwimlaneInAllProcess в ProcessDefinition. потом переопределить.

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/VariableEditorPage.java
> +            	}
Аналогично
Тоже плохое решение, как вариант добавить метод пустой метод removeGlobalSwimlaneInAllProcess в ProcessDefinition. потом переопределить.

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/model/GlobalSectionDefinition.java
> +    private NodeAsyncExecution defaultNodeAsyncExecution = NodeAsyncExecution.DEFAULT;
Переопределять все поля из ProcessDefinistion явно избыточно
Большинство методов также просто копи-паст.  Здесь явно нужно расчистить.

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/view/ProcessExplorerLabelProvider.java
> +            	if (folder.getName().startsWith(".")) {
Предлагаю добавить метод IOUtils.isGlobalSection() и туда вынести проверку.
Думаю логично что isGlobalSection и isProcessDefinistion не должны одновременно возвращать true.

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/view/ProcessExplorerLabelProvider.java
> +        		&& ((IResource) element).getName().startsWith(".")
Предлагаю магию с точкой спрятать в IOUtils  с методом, который бы по названию говорил, зачем это нужно.

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/wizard/ExportGlbWizardPage.java
> +                // TODO getContainer().run
Коммент непонятно зачем

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/util/WorkspaceOperations.java
> +        try {
Точку бы эту хорошо вынести в константы и обозвать типа GLOBAL_PREFIX_DOT или что-то похожее, что бы не пересекаться с GLOBAL_ROLE_REF_PREFIX

2020-06-16 21:27 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/aspects/ProcessEditorUserActivity.aj
>                          GraphElement ge = (GraphElement) ((DiagramEditorPage) editor.getDiagramEditorPage()).getDiagramTypeProvider()
На этом уровне, не очень хорошо, когда такие проверки появляются. 
Специфичное поведение для класса лучше выносить из базовых классов.
Как вариант просто добавить проверку на null, если 
((DiagramEditorPage) editor.getDiagramEditorPage()).getDiagramTypeProvider()  не null, то что-то делать. 
Вроде бы для GlobalSectionEditorBase он должен быть null.

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/plugin.properties
> +VariableUserType.collection.desc.globalSection = Manage user defined types in global section definition scope
Мне казалось, что постфикс desc должен быть в конце названия.

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/plugin.properties
> +VariableNamePage.description.GlobalSection = Variable name must be unique in global section definition and can contain almost any symbols
GlobalSection д.б. с маленькой буквы.
description - это постфикс

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/plugin.properties
> +VariableAccessPage.by.permissions.GlobalSection = Access is defined by read permission on global section
GlobalSection д.б. с маленькой буквы.

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/VariableEditorPage.java
> +        List<Variable> variable_list = getDefinition().getVariables(false, false);
тогда уже variableList

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/VariableEditorPage.java
> +            if (editor.getPartName().startsWith(".")) { // globals
Для точки вроде появилась константа в IOUtils или еще нет.

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/model/ProcessDefinition.java
> +                                    copy.setGlobal(true);*/
Явно мусор в комментах

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/wizard/ImportGlbWizardPage.java
> +                dialog.setFilterExtensions(new String[] { "*.glb" });
Расширение файлов лучше выносить в константы

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/wizard/ExportParWizardPage.java
> +            if (definition != null && !(definition instanceof SubprocessDefinition) && !(definition instanceof GlobalSectionDefinition)) {
если здесь стоит задача отфильтровать наследников. то лучше getClass() == ProcessDefintion.classs

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/UpdateSwimlaneNameDialog.java
> +    	return true;
Сломанный комментарий, наверное на русском плюс еще в кодировке не UTF-8.

2020-06-24 12:39 UTC, technokratos commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/UpdateSwimlaneNameDialog.java
> +        return false;*/
Мусор

2023-05-19 09:20 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-devstudio/commit/ada638779bc1108ad7129958e1d4092ae89e0dbe

2023-05-19 09:20 UTC, closed without merging