Добавлен Пунктирный переход на контекстное меню
processtech/runawfe-devstudio pull request #158
Opened 2020-09-24 15:53 UTC by Dmitry-D-Smirnoff

Добавлен Пунктирный переход на контекстное меню действий для Задачи сценария и Хранилища.
С одной Задачи сценария возможен один переход на Хранилище.
С одного Хранилища возможно несколько переходов на Задачи сценария.
DmitrySmirnoff

2020-09-25 10:40 UTC, AlexMisha requested changes
По коду все хорошо

2020-09-25 10:40 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/DiagramToolBehaviorProvider.java
> +        //TODO: Do we need separate availability check at Node for DottedTransition?
Думаю, нет, т.к. аналогичный флаг используется для создания другого элемента bpmn через контекстное меню, а в постановку входит только добавить пунктирный переход

todo можно убрать

```suggestion
```

2020-09-25 11:14 UTC, Dmitry-D-Smirnoff commented
Спасибо!
Убрал строчку +Commit. 
Сорри, не увидел Suggested change...

2020-09-25 15:05 UTC, AlexMisha approved these changes
:+1:

2023-05-19 09:15 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-devstudio/commit/5ddcd71c5e539000da453359f2a24899c41d51dd

2023-05-19 09:15 UTC, closed without merging