add component SingleSelectFromUserTypeList
processtech/runawfe-devstudio pull request #161
Opened 2020-12-23 12:40 UTC by DesignDeveloperr

2020-12-24 10:43 UTC, AlexMisha requested changes
В соседнем PR оставил просьбу по локальной проверке, все необходимые ссылки вроде предоставил

Просьба тут аналогично проверить и поправить замечания, их в принципе немного

2020-12-24 10:43 UTC, AlexMisha commented on plugins/ru.runa.gpd.form.ftl/plugin.xml
> -            id="varcombo">
Просьба почистить по PR лишние изменения

2020-12-24 10:43 UTC, AlexMisha commented on plugins/ru.runa.gpd.form.ftl/plugin.xml
> +                 variableTypeFilter="java.util.List">
```suggestion
                 variableTypeFilter="ru.runa.wfe.var.UserTypeMap">
```

Потому что на выходе из компонента ожидается 1 элемент, а не список

2020-12-24 10:43 UTC, AlexMisha commented on plugins/ru.runa.gpd.form.ftl/plugin.xml
> +                 type="usertypevarlistcombo"
```suggestion
                 type="varfinder"
```

По-моему так нужно для этого случая
Все доступные типы параметров можно посмотреть вверху этого же файла

2023-05-19 09:13 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-devstudio/commit/bbfde1793b9e7cde10b9e6eccdfc5d49e837e1bf

2023-05-19 09:13 UTC, closed without merging