Feature_2015 implementation draft
processtech/runawfe-devstudio pull request #165
Opened 2021-01-14 08:58 UTC by mikhailal

2021-01-14 09:00 UTC, mikhailal commented
Сделал поддержку переименования объектов перехода в среде разработки.

2021-01-15 14:26 UTC, AlexMisha requested changes
Есть пара замечаний

И просьба проверить код на соответствие style guide, если еще не https://runawfe.org/rus/doc/DevelopersInfo#CodeStyle;

2021-01-15 14:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.properties
> +RenameTransitionDialog.update.title = Rename Transition object
```suggestion
RenameTransitionDialog.update.title = Rename transition
```

Думаю, так достаточно. И соответственно русский перевод - Переименовать переход, если он сейчас не такой

2021-01-15 14:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.xml
> +              label="Переименовать"
label тоже нужен локализация

2021-01-15 14:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameTransitionDelegate.java
> +            PluginLogger.logInfo("Running context menu at Transition: RenameTransition failed\n");
Получается, будет выведена ошибка даже, если пользователь передумал переименовывать переход? Скажем, если он нажал кнопку отмены

2021-01-15 14:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +              Localization.getString("property.name") + ":", "examplename", new IInputValidator() {
Просьба прикрепить сюда пример заголовка, который будет выведен. Смущает `examplename`

2021-01-20 20:32 UTC, AlexMisha requested changes

2021-01-20 20:32 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +                Localization.getString("property.name") + ":", Localization.getString("RenameTransitionDialog.defaultTransitionName"),
Все еще непонятно, как это будет выглядеть. examplename ведь выведется?
Просьба прикрепить скриншот

2021-01-20 20:32 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +        getButton(IDialogConstants.OK_ID).setEnabled(!(Strings.isNullOrEmpty(getText().getText())));
Лишние скобки после !

2021-01-20 20:32 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.xml
> +              id="graph.actions2"
Думаю, можно дать более осмысленное название id

2021-01-20 20:32 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.properties
> +label.action.rename = Rename
Уже есть `button.rename`, можно переиспользовать

2021-01-21 00:12 UTC, mikhailal commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +                Localization.getString("property.name") + ":", Localization.getString("RenameTransitionDialog.defaultTransitionName"),
![изображение](https://user-images.githubusercontent.com/14109544/105256279-82a4ea00-5b96-11eb-919a-6bfbe188abfd.png)

2021-01-21 00:42 UTC, mikhailal commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +        getButton(IDialogConstants.OK_ID).setEnabled(!(Strings.isNullOrEmpty(getText().getText())));
решено 47c1117

2021-01-21 00:42 UTC, mikhailal commented on plugins/ru.runa.gpd/plugin.xml
> +              id="graph.actions2"
решено 47c1117

2021-01-21 00:42 UTC, mikhailal commented on plugins/ru.runa.gpd/plugin.properties
> +label.action.rename = Rename
решено 47c1117

2021-01-21 06:29 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +                Localization.getString("property.name") + ":", Localization.getString("RenameTransitionDialog.defaultTransitionName"),
Ага, понял, как выглядит, спасибо.
Тогда тут стоит выводить текущее название перехода. И в modify listener'е проверять, не пустое ли оно и не соответствует ли новое текущему

2021-01-21 06:30 UTC, AlexMisha requested changes

2021-01-21 06:30 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.xml
> +              id="graph.actions.rename"
```suggestion
              id="graph.actions.rename.transition"
```

?

2021-01-21 09:24 UTC, mikhailal commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +                Localization.getString("property.name") + ":", Localization.getString("RenameTransitionDialog.defaultTransitionName"),
да, да, проглядел это

2021-01-21 15:09 UTC, mikhailal commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +                Localization.getString("property.name") + ":", Localization.getString("RenameTransitionDialog.defaultTransitionName"),
исправил a9ba7a2

2021-01-27 12:26 UTC, AlexMisha requested changes
Пара небольших замечаний

2021-01-27 12:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +        getButton(IDialogConstants.OK_ID).setEnabled(!Strings.isNullOrEmpty(getText().getText()) && !getText().getText().equals(transitionName));
Подозреваю, что вызов `getText().getText()` - не самый дешевый.
В любом случае лучше вынести в локальную переменную

2021-01-27 12:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +    private String transitionName;
Можно сделать `final`

2021-01-27 14:40 UTC, mikhailal commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +    private String transitionName;
исправлено
f7bb585b83373c9b53976d8731861097ef7263a3

2021-01-27 14:40 UTC, mikhailal commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameTransitionDialog.java
> +        getButton(IDialogConstants.OK_ID).setEnabled(!Strings.isNullOrEmpty(getText().getText()) && !getText().getText().equals(transitionName));
исправлено
f7bb585b83373c9b53976d8731861097ef7263a3

2021-01-30 11:04 UTC, AlexMisha approved these changes
:+1:

2023-05-19 09:07 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-devstudio/commit/f09ae9a3f8c3c43df7895d0fa14d026c6cd5fae3

2023-05-19 09:07 UTC, closed without merging