Изменяем поведение таймера по двойном клике мышке на нем.
processtech/runawfe-devstudio pull request #166
Opened 2021-01-15 11:56 UTC by BetterStop

Было: При двойном клике мышки на таймере открывались пареметры действия таймера.
Исправленно: При двойном клике мышки на таймере открываються параметры задердки.

Fix #2029

2021-01-15 14:01 UTC, AlexMisha requested changes
По логике кода вопросов нет

Есть подозрения, что не был применен стиль https://runawfe.org/rus/doc/DevelopersInfo#CodeStyle;
Просьба поправить, если я прав

2021-01-20 18:50 UTC, AlexMisha reviewed
Пара небольших замечаний

2021-01-20 18:50 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/update/DoubleClickTimerFeature.java
> +    	Timer timer = (Timer) getBusinessObject(context);
Тут явно съехало. Либо github так отображает. Просьба проверить

2021-01-20 18:50 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/update/DoubleClickTimerFeature.java
> +                    	UndoRedoUtil.executeFeature(new ChangeTimerDelayFeature(timer, result));
И вот здесь отступ меньше стал

Просьба еще проверить, используется ли где-то `ChangeTimerActionFeature` после удаления использования тут

2021-01-21 04:03 UTC, BetterStop commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/update/DoubleClickTimerFeature.java
> +    	Timer timer = (Timer) getBusinessObject(context);
Да, я заметил, видимо гит так отображает, Если открыт файл на просмотр Files changed -> View File, то там все нормально.

2021-01-21 06:36 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/update/DoubleClickTimerFeature.java
> +    	Timer timer = (Timer) getBusinessObject(context);
Да, посмотрел, все ок

2021-01-21 06:37 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/update/DoubleClickTimerFeature.java
> +                    	UndoRedoUtil.executeFeature(new ChangeTimerDelayFeature(timer, result));
> Просьба еще проверить, используется ли где-то ChangeTimerActionFeature после удаления использования тут

Это еще не смотрели?

2021-01-21 06:38 UTC, AlexMisha approved these changes
:+1: 

Хотелось бы созвониться, чтобы обсудить дальнейшие задачи. Укажите, пожалуйста, предпочтительный способ связи telegram/skype

2021-01-21 06:47 UTC, BetterStop commented on plugins/ru.runa.gpd/src/ru/runa/gpd/editor/graphiti/update/DoubleClickTimerFeature.java
> +                    	UndoRedoUtil.executeFeature(new ChangeTimerDelayFeature(timer, result));
В методе execute класса DoubleClickTimerFeature, после 30 строки, больше  не используется.

2023-05-19 09:05 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-devstudio/commit/05a29d3e99938820ba459f8e14ba7ee8fbc09b5c

2023-05-19 09:05 UTC, closed without merging