Задача 2016
processtech/runawfe-devstudio pull request #167
Opened 2021-02-01 14:11 UTC by Allexandere

2021-02-03 15:26 UTC, AlexMisha requested changes

2021-02-03 15:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.xml
> +             id="ru.runa.gpd.action2"
Лучше давать более осмысленные названия. Например, ru.runa.gpd.rename.node.action

2021-02-03 15:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/Rename.java
> +public class Rename {
Зачем пустые классы? `RenameModel` и `Renamer` тоже касается

2021-02-03 15:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameNodeDialog.java
> +public class RenameNodeDialog extends InputDialog{
Отступ перед { должен быть

2021-02-03 15:26 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +				Localization.getString("InputValue"), null, null);
`initialValue` стоит передать - текущее имя узла.
`validator` - тоже. Чтобы нельзя было сохранить пустое название и равное текущему.

2021-02-06 10:50 UTC, AlexMisha requested changes
Просьба свериться с код стайлом https://runawfe.ru/DevelopersInfo#CodeStyle;

И просьба прикрепить к PR скриншоты, как выглядит выбор действия, как открывается диалог, какие выводятся сообщения в случае невалидного нового имени

2021-02-06 10:50 UTC, AlexMisha commented on plugins/ru.runa.gpd/META-INF/MANIFEST.MF
> +Import-Package: org.eclipse.debug.core,
Полагаю, не относится к задаче

2021-02-06 10:50 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/ui/dialog/RenameNodeDialog.java
> +public class RenameNodeDialog extends InputDialog {
В отдельном классе нет смысла, можно просто `InputDialog` использовать

2021-02-06 10:50 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +					public String isValid(String value) {
Возможно лямбдой сделать?

2021-02-06 10:50 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.xml
> +          objectClass="ru.runa.gpd.lang.model.StartState">
Есть смежная задача - 2014. Возможно если сделать contribution на node, то действие сразу для всех узлов добавится? Думаю, было бы полезно

2021-02-06 21:29 UTC, Allexandere commented on plugins/ru.runa.gpd/plugin.xml
> +          objectClass="ru.runa.gpd.lang.model.StartState">
Возможно, но тогда переиминовать можно будет любой объект из меню. Для EndState и EndTokenState я изменил contribution на AbstractEndTextDecorated.

2021-02-06 21:29 UTC, Allexandere commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +					public String isValid(String value) {
да

2021-02-06 23:12 UTC, Allexandere commented
![photo_2021-02-07_02-09-27 (2)](https://user-images.githubusercontent.com/39259989/107131707-e85cda00-68e9-11eb-8328-7d25c788af13.jpg)
![photo_2021-02-07_02-09-27](https://user-images.githubusercontent.com/39259989/107131711-ea269d80-68e9-11eb-8f2b-ac87a25af337.jpg)
![photo_2021-02-07_02-09-28 (2)](https://user-images.githubusercontent.com/39259989/107131712-eabf3400-68e9-11eb-8721-9c2011dc5f19.jpg)
![photo_2021-02-07_02-09-28 (3)](https://user-images.githubusercontent.com/39259989/107131713-eabf3400-68e9-11eb-8029-4921ca4e713e.jpg)
![photo_2021-02-07_02-09-28 (4)](https://user-images.githubusercontent.com/39259989/107131714-eb57ca80-68e9-11eb-852a-c984d50044ae.jpg)
![photo_2021-02-07_02-09-28 (5)](https://user-images.githubusercontent.com/39259989/107131715-ebf06100-68e9-11eb-8d31-0d9173e255ab.jpg)
![photo_2021-02-07_02-09-28](https://user-images.githubusercontent.com/39259989/107131716-ebf06100-68e9-11eb-9c78-5160aeba5b00.jpg)

2021-02-07 04:40 UTC, Allexandere commented
![Демонстрация](https://user-images.githubusercontent.com/39259989/107136846-c0846b00-6917-11eb-826a-c001dbbf71eb.gif)

2021-02-09 15:44 UTC, AlexMisha requested changes

2021-02-09 15:44 UTC, AlexMisha commented on plugins/ru.runa.gpd/META-INF/MANIFEST.MF
> +Import-Package: org.eclipse.debug.core,
Имел ввиду, что надо бы убрать из PR, если к задаче не относится

2021-02-09 15:44 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +                        return Localization.getString("VariableNamePage.error.duplicated", value);
Тут стоит вывести другое сообщение, вроде "Новое имя не должно совпадать со старым"

2021-02-09 15:44 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +                    if (value.trim().isEmpty()) {
`trim` - не самая дешевая операция, чтобы повторять ее 2 раза подряд (ниже в if).
Стоит выделить в локальную переменную

2021-02-09 15:44 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +        renameNodeDialog.open();
По-моему можно было сравнивать результат вызова `open` с константой типа `OK`
Тогда не придется дополнительно валидировать значение ниже, т.к. кнопка ОК доступна только, если валидация пройдена

2021-02-09 15:44 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +            if (newName != null && !newName.trim().equals(""))
У нас фигурные скобки всегда ставятся

2021-02-11 13:30 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/RenameAction.java
> +        renameNodeDialog.open();
https://www.programcreek.com/java-api-examples/org.eclipse.jface.dialogs.InputDialog

`inputDialog.open() == InputDialog.OK`

2021-02-11 14:09 UTC, AlexMisha approved these changes
:+1:

2021-03-10 12:26 UTC, closed without merging