Selection in process editor by double click on search results (form and
processtech/runawfe-devstudio pull request #168
Opened 2021-02-01 22:08 UTC by mzub

form validation) has been added

2021-02-03 11:55 UTC, AlexMisha requested changes
Одно небольшое замечание

2021-02-03 11:55 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/search/SearchPage.java
> +    private void selectFormOrFormValidation(ElementMatch elementMatch) {
```suggestion
    private void selectFormNode(ElementMatch elementMatch) {
```
Мне кажется это название больше соответствует смыслу метода, т.к. он фокусируется на узле формы вне зависимости от того, как его вызвали.

2021-02-03 16:21 UTC, mzub commented
Я поправил название метода и его вызовы

2021-02-04 09:53 UTC, AlexMisha requested changes

2021-02-04 09:53 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/search/SearchPage.java
> +		ProcessEditorBase processEditor = WorkspaceOperations.openProcessDefinition(elementMatch.getParent().getFile());
Тут явно слишком большой отступ. Просьба свериться с код стайлом https://runawfe.ru/DevelopersInfo#CodeStyle;

2021-02-04 17:52 UTC, mzub commented on plugins/ru.runa.gpd/src/ru/runa/gpd/search/SearchPage.java
> +		ProcessEditorBase processEditor = WorkspaceOperations.openProcessDefinition(elementMatch.getParent().getFile());
пофиксил. это видимо из-за vim wrapper

2021-02-05 08:45 UTC, AlexMisha approved these changes
:+1:

2023-05-09 13:24 UTC, closed without merging