Добавлен новый элемент "Бизнес-правило"
processtech/runawfe-devstudio pull request #169
Opened 2021-04-01 04:23 UTC by zin1995

Добавлен новый элемент "Бизнес-правило". Был изменен модификатор доступа FormulaCellEditorProvider.ConfigurationDialog на public, чтобы избежать дублирования кода.

2021-04-06 12:46 UTC, AlexMisha requested changes

2021-04-06 12:46 UTC, AlexMisha commented on plugins/ru.runa.gpd/schema/Semantic.xsd
> +	<xsd:element name="businessRule" type="tBusinessRule" substitutionGroup="flowElement"/>
Этот файл мы обычно не меняем, т.к. это файл схемы-стандарта BPMN
Вижу, что есть `businessRuleTask`, он чем-то не подошел?

2021-04-06 12:46 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +public class BusinessRuleEditorDialog extends Dialog {
Насколько понимаю, класс +/- полностью копирует `GroovyEditorDialog`?
Может, получится выделить общую часть, а остальное с помощью наследования/делегирования выразить?

И есть явные несоответствия код стайлу, просьба сверить весь pr с https://runawfe.ru/DevelopersInfo#CodeStyle;

2021-04-06 12:46 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
> +		if (!(delegable instanceof BusinessRule)) {
По-моему было достаточно поставить `actioHandler='false'` в конфигурациии

2021-04-06 12:46 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.xml
> +            enabled="false"
А точно ли нужно прописывать сюда обработчик, если он не будет использоваться ни из задач сценария, ни из задач ботов?

2021-04-13 13:15 UTC, zin1995 commented on plugins/ru.runa.gpd/schema/Semantic.xsd
> +	<xsd:element name="businessRule" type="tBusinessRule" substitutionGroup="flowElement"/>
Отменил изменения, сделал с помощью businessRuleTask, вроде все ок

2021-04-13 13:16 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +public class BusinessRuleEditorDialog extends Dialog {
кодстайл поправил. На счет наследования, да, могу исправить, но поля классов отличаются, это не проблема?

2021-04-13 13:17 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
> +		if (!(delegable instanceof BusinessRule)) {
Это было заглушкой, не мог разобраться как убрать лишний пункт меню, сделал просто не активным. Сейчас исправил

2021-04-13 13:18 UTC, zin1995 commented on plugins/ru.runa.gpd/plugin.xml
> +            enabled="false"
Если сделать actioHandler='false' в DS всплывает замечание - "класс обработчика не найден". А без этой конфигурации вообще не работает %)

2021-04-27 08:29 UTC, AlexMisha requested changes

2021-04-27 08:29 UTC, AlexMisha commented on plugins/ru.runa.gpd/plugin.xml
> +            icon="bussiness-pravilo.png"
`business-rule.png`? И сам файл соответственно тоже желательно переименовать

2021-04-27 08:29 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +public class BusinessRuleEditorDialog extends Dialog {
Тут скорее надо выделять общую часть и с помощью наследования кастомизировать поведение

2021-04-27 08:29 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
>  public class ChooseDelegableHandlerAction extends BaseModelActionDelegate {
Лишние diff'ы в классе

2021-05-11 08:23 UTC, AlexMisha requested changes

2021-05-11 08:23 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
>  public class ChooseDelegableHandlerAction extends BaseModelActionDelegate {
Все еще лишние diff'ы

2021-05-11 08:23 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Класс сильно отличается от `GroovyDecisionModel`? По идее не должен, стоит выделить общую часть

2021-05-11 08:23 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +    private Composite createButtomComposite() {
```suggestion
    private Composite createBottomComposite() {
```

2021-05-11 08:23 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +        FilterBox[] var = new FilterBox[2];
`var` - не слишком удачное имя, стоит отразить в названии, зачем нужна переменная

2021-05-11 08:23 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +        Combo oper = new Combo(constructor, SWT.READ_ONLY);
`operations`? Сокращения иногда могут сбить с толку

2021-05-11 08:23 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                Variable variable = ifExpr.getVariable1();
Тоже просьба отразить в названии, что это за переменная и что за индекс идет ниже

2021-05-11 08:23 UTC, AlexMisha commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +            if (indexes[1] == 2) {
`indexes` - название стоит конкретизировать
И почему == именно 2? Мне это кажется не очевидным, стоит оставить комментарий

2021-05-11 09:04 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
>  public class ChooseDelegableHandlerAction extends BaseModelActionDelegate {
похоже не запушил, исправлю

2021-05-12 08:40 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +    private Composite createButtomComposite() {
спасибо! я пол часа убил чтобы понять в чем разница в строках, не представляю как ты смог найти эту опечатку в коде)

2021-05-12 08:59 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
>  public class ChooseDelegableHandlerAction extends BaseModelActionDelegate {
в проекте удалено, здесь почему-то не отображается...

2021-05-12 12:38 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                Variable variable = ifExpr.getVariable1();
Тут просто локальная переменная для заполнения FilterBox, index тоже служебная переменная в FilterBox - просто порядковый номер элемента в массиве. То есть более говорящих имен и не подберешь.

2021-05-12 16:28 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +            if (indexes[1] == 2) {
тоже просто локальная переменная индекса поля, не знаю даже нужно ли конкретизировать

2021-05-12 16:32 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Они вообще практически идентичны, в основном только строка с именем transition заменена на строку function. Делема, как назвать эту переменную в их общем классе?)

2021-05-13 13:17 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Этот момент пока отложу, получил задачу, скорее всего буду сильно менять BusinessRuleModel

2021-07-15 13:39 UTC, CrimsonParade requested changes
Каждое сокращение отмечать не стал, просьба пройтись по всему классу и попереименовывать в полные формы (особенно `Expr` -> `Expression`)

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +            FilterBox targetFB;
Аббревиатуры тоже следует писать в camel case: "targetFB -> targetFb"
https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

Тут, на мой взгляд, лучше будет вообще без оных: `fb`/`targetFB` -> `box`/`targetBox`

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +            int varNum = indexData[2] == 0 ? 0 : 1;
Множество `Magic Numbers`, которые используются по всему классу, может быть стоит вынести в константы с понятными названиями? (тогда и комментировать их не нужно будет)
Читаться будет в разы быстрее и проще

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +    public class SyncOperComboHandler extends SelectionAdapter {
Желательно избегать сокращений, особенно в названиях классов/методов

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +    private void createExpr(Composite parent, int indexLine) {
`Expression` тоже лучше писать полностью (и в названии метода, и в названиях переменных)

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +        int indexExpr = exprLine.getVariableBoxes().indexOf(variable);
`expressionIndex` будет правильнее

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +        FilterBox[] variable = new FilterBox[2];
`variables`?

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +        logicBox.setItems("null", "and", "or");
Как и с `Magic Numbers`, следует вынести в константы

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                // indexes[1] == 2 - second variable
Последствия `Magic Numbers`: не только приходится писать комментарии, но они еще и расходятся с кодом
 (в коде - `indexes[2]`, в комменте - `indexes[1]`)

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                if (exprLine.getVariableBoxes().get(j)[0].getText().length() == 0 || exprLine.getVariableBoxes().get(j)[1].getText().length() == 0
Достаточно длинное условие, заставляющее долго в него вникать и писать комментарии. 
На мой взгляд, лучше вынести в переменную (что-то вроде `dataIsEmpty`) - тогда и комментарий будет излишним, и читать будет проще.

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                List<Variable> variable1list = new ArrayList();
Не очень нравится название, может быть что-то вроде `firstVariables` или `leftVariables`?

2021-07-15 13:39 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                List<Object> lexem2list = new ArrayList();
`secondLexems`/`rightLexems`?

2021-07-15 13:41 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +            if (indexes[1] == 2) {
Может быть `variableIndexes`?

2021-07-15 13:41 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
>  public class ChooseDelegableHandlerAction extends BaseModelActionDelegate {
Возможно, автоформатирование в IDE?

2021-07-15 13:42 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Все еще актуально, в классах достаточно много общего

2021-08-15 13:39 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Если честно, не совсем понимаю стоит ли это делать. Классы похожи структурно, но отличаются логически. Мне кажется если их унифицировать, это только усложнит читаемость и понимание кода.

2021-08-24 12:58 UTC, CrimsonParade requested changes
Плюс осталось два нерешенных вопроса с предыдущего ревью: 
если пропущено сознательно, просьба написать, по какой причине.

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +    private static final int FIRST_VARIABLE_INDEX = 0;
Константы принято располагать в начале класса (над "обычными" полями)

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +        FilterBox[] variable = new FilterBox[2];
Как-то неправильно понял или все-таки это массив переменных?

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                    firstVariableIndex = Operation.getAll(typeSupport).indexOf(ifExpr.getOperations().get(j));
Думаю, не стоит переиспользовать `firstVariableIndex`, лучше будет добавить `operationIndex`.
В противном случае, если читать по диагонали, далеко не очевидно, почему условие `(firstVariableIndex == -1)` встречается дважды.

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                    if (VariableUtils.getVariableByScriptingName(variables, secondVariableText) != null
Достаточно объемное условие - стоит вынести в переменную (по аналогии с `emptyFieldExist`)

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                Combo operCombo = expressionLines.get(indexes[0]).getOperationBoxes().get(indexes[1]);
`operationCombo`/`operations`

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleEditorDialog.java
> +                    Object secondVariable;
`Object` как тип переменной не нравится, да и название `variable2` возникает из-за этого же.

Кажется, так будет лучше (вместо вязанки if'ов, связанной с инициализацией `secondVariable`):
```suggestion
                    Variable secondVariable = VariableUtils.getVariableByScriptingName(variables, secondVariableText);  
                    if (secondVariable != null && secondVariable.getJavaClassName().equals(firstVariable.getJavaClassName())) {
                        secondVariables.add(secondVariable);
                    } else {
                        secondVariables.add(secondVariableText);
                    }
```

Ниже, соответсвенно, `secondVariables.add(secondVariable);` убрать

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +    protected List<String> getSecondVariableNames(Variable variable1) {
Обычно, если в названии появляются числа, можно придумать что-то более подходящее.

Тут, судя по использованию, в качестве параметра приходит `firstVariable`?
Если так, то напрашивается переименование `variable1` -> `firstVariable`, 
а ниже, соответственно, `typeSupport1` -> `firstVariableTypeSupport`.

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +    protected static final String DATA_INDEX_KEY = "indexes";
Аналогично `BusinessRuleEditorDialog`, константы стоит перенести наверх.

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +            // Activate source view if custom code found
Выглядит как `Control Flow Exceptions` - стоит подумать, как можно от этого избавиться.

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +        TabItem tabItem2 = new TabItem(tabFolder, SWT.NONE);
Более конкретное название? (можно отталкиваться от `GroovyEditor.title.code`)

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +        TabItem tabItem1 = new TabItem(tabFolder, SWT.NONE);
Более конкретное название? (можно отталкиваться от `GroovyEditor.title.constructor`)

2021-08-24 12:58 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Глубоко не вникал, но на первый взгляд не видно каких-то серьезных различий в бизнес-логике классов.
Можешь расписать чуть подробнее, в чем они состоят?

2021-08-24 13:12 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Мы можем пообщаться в телеграмме?

2021-08-24 13:34 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
В основном разный нейминг методов, связанный с тем, что в одном случае мы работаем с "именем перехода", а в другом с формулой. Плюс наличие во внутреннем классе различающийся полей, то есть обращаться к ним придется все равно явно указывая тип класса. Различия в конструкторе плотно связанны с телом, то есть выделить общую часть проблематично, разве что выносить ее в отдельный метод. Мне кажется выделение общей части только усложнит понимание логики обоих классов.

2021-08-24 14:08 UTC, zkvan commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +    protected List<String> getSecondVariableNames(Variable variable1) {
Подобный нейминг выбирал не я, просто перенес его при выделении общей части классов. Стоит ли мне тогда внести аналогичные изменения в GroovyEditorDilog и в GroovyDecisionModel?

2021-08-24 16:41 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Да, можно в телегу: t.me/ExDeathX

Если взять, например, конструктор, то там разница только в названии переменной (`function` вместо `transition`) и 
в том, где в объекте хранится эта переменная (инициализация `defaultFunction` вместо `addIfExpr()`).
Имхо, выделить общую часть будет полезно, ибо классы, по сути своей, занимаются одним и тем же, но с разными объектами предметной области => в обсуждаемых классах логичнее видеть только специфические поля/методы, а не дублирование функционала.

2021-08-24 16:57 UTC, CrimsonParade commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +    protected List<String> getSecondVariableNames(Variable variable1) {
Да, к сожалению, в старом коде тоже встречаются проблемы :)
Общее правило звучит примерно так: 
"Если проблемы находятся в той части, что изменяется, попутный рефакторинг - добро, если нет - трогать не стоит (лишние мерж-конфликты)".
`GroovyEditorDialog`, судя по diff'y, постигли довольно серьезные изменения - думаю, самые простые ренеймы не будут лишними.
 `GroovyDecisionModel`, если решим выделять общую часть, тоже весьма сильно изменится => при выделении общей части можно будет позволить себе подпричесать и код в целом, и названия в частности.

2021-09-15 02:15 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/businessRule/BusinessRuleModel.java
> +public class BusinessRuleModel implements GroovyModel {
Конструктор GroovyDecidionModel не поддерживает множественные условия, соответственно механизм парсинга отличается. Из всего класса, безболезненно, получится выделить в общий класс только get и setIfExp методы, и normalizeString. Остальное завязано на различие во внутреннем классе (тоже используются массивы для переменных, вместо их одиночного хранения) и на разнице в нейминге (function и transition), которые тоже на мой взгляд менять нельзя, тк имена говорящие.

2021-10-01 01:28 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/extension/decision/GroovyEditorDialogType.java
> +            // Activate source view if custom code found
В данном случае это выглядит каким-то костылем, без какой-либо полезного применения. Решил просто удалить)

2021-10-01 01:33 UTC, zin1995 commented on plugins/ru.runa.gpd/src/ru/runa/gpd/lang/action/ChooseDelegableHandlerAction.java
>  public class ChooseDelegableHandlerAction extends BaseModelActionDelegate {
В форке репо "zin1995 / runawfe-free-devstudio" лишнего нету, не могу понять почему тут отображается.

2022-08-30 04:33 UTC, closed without merging